services:
    anca_rebeca_full_calendar.service.serializer:
        class: AncaRebeca\FullCalendarBundle\Service\Serializer
        public: false

    anca_rebeca_full_calendar.service.calendar:
        class: AncaRebeca\FullCalendarBundle\Service\Calendar
        public: true
        arguments:
            - "@anca_rebeca_full_calendar.service.serializer"
            - "@event_dispatcher"
